# -*- mode: ruby -*-
# vi: set ft=ruby :
# https://docs.vagrantup.com

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
   config.vm.box_check_update = true
   config.vm.synced_folder ".", "/vagrant"
   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.name = "my_kali"
     vb.cpus = 2
     vb.memory = "2048"
   end
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update && apt-get full-upgrade -y
  # SHELL
end
